[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]
solc = "0.8.20"

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
polygon_mumbai = "https://rpc-mumbai.polygon.technology"
base = "https://mainnet.base.org"
mainnet = "https://eth.llamarpc.com"

[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
arbitrum_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }
polygon_mumbai = { key = "${ETHERSCAN_API_KEY}", url = "https://api-testnet.polygonscan.com/api" }
base = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api" }